src/main/java/io/a2a/spec/A2AClientError.java
src/main/java/io/a2a/spec/A2AClientHTTPError.java
src/main/java/io/a2a/spec/A2AClientJSONError.java
src/main/java/io/a2a/spec/ContentTypeNotSupportedError.java
src/main/java/io/a2a/spec/InternalError.java
src/main/java/io/a2a/spec/InvalidParamsError.java
src/main/java/io/a2a/spec/InvalidRequestError.java
src/main/java/io/a2a/spec/JSONParseError.java
src/main/java/io/a2a/spec/JSONRPCError.java
src/main/java/io/a2a/spec/MethodNotFoundError.java
src/main/java/io/a2a/spec/MissingAPIKeyError.java
src/main/java/io/a2a/spec/PushNotificationNotSupportedError.java
src/main/java/io/a2a/spec/TaskNotCancelableError.java
src/main/java/io/a2a/spec/TaskNotFoundError.java
src/main/java/io/a2a/spec/UnsupportedOperationError.java
src/main/java/io/a2a/util/Utils.java
src/test/java/io/a2a/client/A2AClientTest.java

Add error classes

---

README.md
src/main/java/io/a2a/client/A2AClient.java
src/main/java/io/a2a/spec/CancelTaskRequest.java
src/main/java/io/a2a/spec/GetTaskPushNotificationRequest.java
src/main/java/io/a2a/spec/GetTaskRequest.java
src/main/java/io/a2a/spec/TaskIdParams.java
src/main/java/io/a2a/spec/TaskQueryParams.java
src/main/java/io/a2a/spec/TaskState.java
src/test/java/io/a2a/client/A2AClientTest.java
src/test/java/io/a2a/client/JsonMessages.java

Closes: 
* https://github.com/fjuma/a2a-java-sdk/issues/14
* https://github.com/fjuma/a2a-java-sdk/issues/15
* https://github.com/fjuma/a2a-java-sdk/issues/16

Implement A2AClient getTask, cancelTask, and getTaskPushNotificationConfig

---

README.md
src/main/java/io/a2a/client/A2AClient.java
src/main/java/io/a2a/spec/PushNotificationConfig.java
src/main/java/io/a2a/spec/SetTaskPushNotificationRequest.java
src/test/java/io/a2a/client/A2AClientTest.java
src/test/java/io/a2a/client/JsonMessages.java

Closes https://github.com/fjuma/a2a-java-sdk/issues/17

Implement A2AClient#setTaskPushNotificationConfig

---

README.md
src/main/java/io/a2a/client/A2AClient.java
src/main/java/io/a2a/spec/A2A.java
src/test/java/io/a2a/client/A2AClientTest.java
src/test/java/io/a2a/client/JsonMessages.java

Closes https://github.com/fjuma/a2a-java-sdk/issues/7 and https://github.com/fjuma/a2a-java-sdk/issues/11

Add a utility method that can be used to fetch an agent card

---

src/main/java/io/a2a/server/agentexecution/RequestContext.java
src/main/java/io/a2a/spec/Message.java

Closes https://github.com/fjuma/a2a-java-sdk/issues/54

Add a RequestClass

---

README.md
pom.xml
src/main/java/io/a2a/examples/helloworld/HelloWorldClient.java
src/main/java/io/a2a/examples/helloworld/HelloWorldRunner.java
src/main/java/io/a2a/examples/helloworld/INSTALL_JBANG.md
src/main/java/io/a2a/examples/helloworld/README.md

It doesn't work, and we need to discuss about this

example of java client running against python server

---

tck/src/main/java/io/a2a/examples/helloworld/server/AgentExecutorProducer.java

Fire and forget task execution

---

core/src/test/java/io/a2a/client/A2AClientTest.java
core/src/test/java/io/a2a/client/JsonMessages.java

for issue task https://github.com/a2aproject/a2a-java/issues/20

test: update A2AClientTest with sending FilePart and DataPart

---

.github/workflows/build-and-test.yml

-----
This is an initial pass essentially running `mvn package`. I think we can and should also run the TCK, but that will come later. I'm just back after a week off, so I need to understand better where we are first

test(ci): Basic CI to build the project and run the tests

---

sdk-server-common/src/main/java/io/a2a/server/util/async/AsyncExecutorProducer.java
sdk-server-common/src/main/resources/META-INF/beans.xml

@ApplicationScoped so that it becomes a stereotype and can be discovered using bean-discovery-mode="annotated" instead of "all".
- [C] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [C] Ensure the tests pass
Fixes …

fix: Moving the AsyncExecutorProducer from @Singleton to

---

README.md
client/pom.xml
common/pom.xml
examples/helloworld/client/pom.xml
examples/helloworld/client/src/main/java/io/a2a/examples/helloworld/HelloWorldRunner.java
examples/helloworld/pom.xml
examples/helloworld/server/pom.xml
pom.xml
sdk-jakarta/pom.xml
sdk-quarkus/pom.xml
sdk-quarkus/src/main/java/io/a2a/server/apps/quarkus/A2AServerRoutes.java
sdk-server-common/pom.xml
spec/pom.xml
tck/pom.xml
tests/server-common/pom.xml

chore: Get ready to deploy to Maven Central using temporary groupId

---

client/pom.xml
common/pom.xml
examples/helloworld/client/pom.xml
examples/helloworld/client/src/main/java/io/a2a/examples/helloworld/HelloWorldRunner.java
examples/helloworld/pom.xml
examples/helloworld/server/pom.xml
pom.xml
sdk-jakarta/pom.xml
sdk-quarkus/pom.xml
sdk-server-common/pom.xml
spec/pom.xml
tck/pom.xml
tests/server-common/pom.xml

chore: Prepare 0.2.3.Beta1 release

---

client/src/main/java/io/a2a/client/A2ACardResolver.java
client/src/test/java/io/a2a/client/A2ACardResolverTest.java
reference-impl/src/main/java/io/a2a/server/apps/quarkus/A2AServerRoutes.java
sdk-server-common/src/main/java/io/a2a/server/tasks/ResultAggregator.java

This PR incorporates the latest feedback from https://github.com/a2aproject/a2a-java/pull/138.

fix: Incorporate latest feedback from https://github.com/a2aproject/a2a-java/pull/138

---

.github/workflows/build-and-test.yml
.github/workflows/run-tck.yml

chore: make workflows manually runnable

---

tck/src/main/java/io/a2a/tck/server/AgentExecutorProducer.java

- [ x] Follow the [`CONTRIBUTING` Guide](../CONTRIBUTING.md).
- [ x] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [ x] Ensure the tests pass
- [ x] Appropriate READMEs were updated (if necessary)

Fix: this is a fix for a2a-tck issue 36

---

.github/conventional-commit-lint.yaml
.github/release-please.yml
.github/release-trigger.yml
.github/workflows/conventional-commits.yml
.github/workflows/release-please.yml

Google GitHub Apps will be shut down

ci: Convert Conventional Commits and Release Please to GitHub Actions

---

README.md

Fixes outdated link to samples README

fix: Link to examples in README.md

---

examples/helloworld/client/src/main/java/io/a2a/examples/helloworld/HelloWorldClient.java
examples/helloworld/server/pom.xml
examples/helloworld/server/src/main/java/io/a2a/examples/helloworld/AgentCardProducer.java

fix: Update the examples after the latest client changes

---

README.md

fix: Update JSONRPCTransportConfig option in README

---

.github/workflows/run-tck.yml
reference/grpc/src/test/java/io/a2a/server/grpc/quarkus/QuarkusA2AGrpcTest.java
reference/grpc/src/test/resources/application.properties
tck/src/main/resources/application.properties

feat: Use main HTTP port for gRPC

---

.github/workflows/run-tck.yml

chore: Update to a2a-tck 0.3.0.beta

---

server-common/src/test/java/io/a2a/server/agentexecution/RequestContextTest.java
server-common/src/test/java/io/a2a/server/tasks/TaskUpdaterTest.java
spec/src/main/java/io/a2a/spec/Message.java
transport/jsonrpc/src/test/java/io/a2a/transport/jsonrpc/handler/JSONRPCHandlerTest.java

fix: Ensure messageId is required for a Message. Allow the messageId to be randomly generated if not set when using the Message.Builder

---

README.md

fix: Update transport descriptions in README

---

.gitignore

So users can experiment with their own CLAUDE.md files, until we have an official one (if ever)

chore: Add .claude to .gitignore
